apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    postgres-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvYW5hbHl0aWNz
    postgres-password: cG9zdGdyZXM=
    postgres-username: cG9zdGdyZXM=